export const engToUkr = {
  a: 'а',
  b: 'б',
  c: 'ц',
  d: 'д',
  e: 'е',
  f: 'ф',
  g: 'г',
  h: 'х',
  i: 'і',
  j: 'й',
  k: 'к',
  l: 'л',
  m: 'м',
  n: 'н',
  o: 'о',
  p: 'п',
  q: 'кв',
  r: 'р',
  s: 'с',
  t: 'т',
  u: 'у',
  v: 'в',
  w: 'в',
  x: 'кс',
  y: 'и',
  z: 'з'
}

export const ukrToEng = {
  а: 'a',
  б: 'b',
  в: 'v',
  г: 'h',
  ґ: 'g',
  д: 'd',
  е: 'e',
  є: 'ie',
  ж: 'zh',
  з: 'z',
  и: 'y',
  і: 'i',
  ї: 'i',
  й: 'i',
  к: 'k',
  л: 'l',
  м: 'm',
  н: 'n',
  о: 'o',
  п: 'p',
  р: 'r',
  с: 's',
  т: 't',
  у: 'u',
  ф: 'f',
  х: 'kh',
  ц: 'ts',
  ч: 'ch',
  ш: 'sh',
  щ: 'shch',
  ь: '',
  ю: 'iu',
  я: 'ia',
  А: 'A',
  Б: 'B',
  В: 'V',
  Г: 'H',
  Ґ: 'G',
  Д: 'D',
  Е: 'E',
  Є: 'IE',
  Ж: 'ZH',
  З: 'Z',
  И: 'Y',
  І: 'I',
  Ї: 'I',
  Й: 'I',
  К: 'K',
  Л: 'L',
  М: 'M',
  Н: 'N',
  О: 'O',
  П: 'P',
  Р: 'R',
  С: 'S',
  Т: 'T',
  У: 'U',
  Ф: 'F',
  Х: 'KH',
  Ц: 'TS',
  Ч: 'CH',
  Ш: 'SH',
  Щ: 'SHCH',
  Ь: '',
  Ю: 'IU',
  Я: 'IA'
}

export const engDigraphsToUkr = {
  zh: 'ж',
  sh: 'ш',
  ch: 'ч',
  kh: 'х',
  ts: 'ц',
  ya: 'я',
  ye: 'є',
  yi: 'ї',
  yu: 'ю',
  ia: 'я'
}

export const tranlitRegionsToCyr = {
  'Krym, Avtonomna Respublika': 'Автономна Республіка Крим',
  'Vinnytska Oblast': 'Вінницька',
  'Volynska Oblast': 'Волинська',
  'Dnipropetrovska Oblast': 'Дніпропетровська',
  'Donetska Oblast': 'Донецька',
  'Zhytomyrska Oblast': 'Житомирська',
  'Zakarpatska Oblast': 'Закарпатська',
  'Zaporizka Oblast': 'Запорізька',
  'Ivano-Frankivska Oblast': 'Івано-Франківська',
  'Kyivska Oblast': 'Київська',
  'Kirovohradska Oblast': 'Кіровоградська',
  'Luhanska Oblast': 'Луганська',
  'Lvivska Oblast': 'Львівська',
  'Mykolaivska Oblast': 'Миколаївська',
  'Odeska Oblast': 'Одеська',
  'Poltavska Oblast': 'Полтавська',
  'Rivnenska Oblast': 'Рівненська',
  'Sumska Oblast': 'Сумська',
  'Ternopilska Oblast': 'Тернопільська',
  'Kharkivska Oblast': 'Харківська',
  'Khersonska Oblast': 'Херсонська',
  'Khmelnytska Oblast': 'Хмельницька',
  'Cherkaska Oblast': 'Черкаська',
  'Chernihivska Oblast': 'Чернівецька',
  'Chernivetska Oblast': 'Чернігівська область',
  'Kyiv, Misto': 'Київ, місто',
  'Sevastopol, Misto': 'Ісевастополь, Місто'
}
